services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=fcordero@acid.cl
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'
    depends_on:
      - postgres
  postgres:
    build: './database'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    restart: always
    ports:
      - '5432:5432'
  nats:
    image: "nats-streaming:0.9.2"
    restart: always
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.3"
    environment:
      - "discovery.type=single-node"
  feed:
    build: "."
    command: "feed-service"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
      NATS_ADDRESS: "nats:4222"
  query:
    build: "."
    command: "query-service"
    depends_on:
      - "postgres"
      - "nats"
      - "elasticsearch"
    ports:
      - "8080"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: mysecretpassword
        POSTGRES_DB: mydb
        NATS_ADDRESS: "nats:4222"
        ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
  pusher:
    build: "."
    command: "pusher-service"
    depends_on:
      - "nats"
    ports:
      - "8080"
    environment:
      NATS_ADDRESS: "nats:4222"